### ISSUE TITLE
ISO-8601 dates

### ISSUE THREAD

**Issue by OxygenCobalt** [OxygenCobalt/Auxio#159]
This feature is about implementing ISO-8601 dates in Auxio. Previously, I was limited to a year value, but with #128, I could feasibly extract the entire date from a file.

This is how the feature will work:
- Sorting will be done by the fine-grained dates.
- Years will still be the only item shown in the UI, for simplicity.
- If #128 is not enabled, the current behavior will stay.

**Comment by foss-** [comment]
With this issue fixed does that mean id3v2.4 is still having the same problem filed in android tracker as https://issuetracker.google.com/issues/238425624?

**Comment by OxygenCobalt** [comment]
Nope. That issue is completely solved now with the new parser @foss-.

**Comment by foss-** [comment]
2.6.1 made it to F-Droid. Should ID3v2.4 tagged mp3s show with year now? They still show `No date`. Not quite sure what's currently to be expected.

**Comment by OxygenCobalt** [comment]
You have to enable "Ignore MediaStore tags" in settings for now until #207 is implemented. @foss-

**Comment by OxygenCobalt** [comment]
Update: UI changes that I've made may have freed up enough space for me to show a more precise date within the UI. Instead of just "2020", I could maybe show "August 1st, 2020" instead. Depends on how it fits.

**Comment by OxygenCobalt** [comment]
In 3.0.0, finer-grained dates will show an (abbreviated) month value within the UI. Currently this only works on Android O onwards, but once I can work my way around the awful legacy date API I think I can back-port it.

![image](https://user-images.githubusercontent.com/65370175/197315013-bcc0481f-7911-4de1-9368-85227ecd13a3.png)
