### ISSUE TITLE
skipping (foreground, main player ui) sometimes crashes the app

### ISSUE THREAD

**Issue by KraXen72** [OxygenCobalt/Auxio#273]
#### Describe the bug/crash:
App crashes when skipping fast/sometimes skipping at all

#### Expected behavior
app doesn't crash

#### Steps To Reproduce the bug/crash:
i know this sounds like a nightmare to reproduce, but sometimes, when i skip too fast or at all, the app crashes.
it happened on some particular songs more than once, but now it's happening with other songs occasionally as well.

the crash occurs right after a skip, the new song does not start playing, nor does the album art load.

it happened like 3 times today and I've used auxio for maybe 2-3 hours (mostly background play, crash only occurs while in foreground)

also sometimes it happens a few times in a short span of time (30s). i reopen to skip and it crashes again

#### Logs/Stack Traces:
- none

#### Screenshots:
- couldn't capture

#### Phone Information:
- samsung galaxy m21
- android 12 oneui 4.2
- niagara launcher

#### Due Diligence:
- [x] I have checked this issue for any duplicates.
- [x] I have checked for this issue in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I think this is already tracked by #239. Basically, ExoPlayer can report a position as -1, which I didn't properly handle in the UI, causing a crash since the SeekBar does not gracefully degrade with invalid positions. I've fixed it in the in-dev version, but since the current version I'm working on is 3.0.0, it may take a bit to release.

I'm considering making a 2.6.4 hotfix that resolves this issue (and some others), but I have had no time to work on Auxio recently.

**Comment by OxygenCobalt** [comment]
It's also basically identical to #231. I don't quite understand why it occurs in background play, but I'm certain that it's because the UI still active for whatever reason and can crash.

**Comment by illdeletethis** [comment]
for me the crash happens with the full screen player skip buttons in both directions, every time, as well as with the position scroll bar setting position to 0.
using the forward only skip from the bottom bar or either direction of the notification skip buttons is fine.
should you have the time for it, 2.6.4 would be appreciated, since this is quite a frustrating issue.

**Comment by OxygenCobalt** [comment]
Yikes, that's really bad. Never experienced it on my end, since apparently the -1 behavior dis basically encoder and device dependent. I'll try to push out something soon.

**Comment by OxygenCobalt** [comment]
I think I'll have enough leeway to push a 2.6.4 out *next* weekend. Midterms are eating up all my time right now...

**Comment by OxygenCobalt** [comment]
Care to test this? It's a pretty mild band-aid, but I think it should resolve the issue. @KraXen72 @illdeletethis 

[Auxio_Fix.zip](https://github.com/OxygenCobalt/Auxio/files/9996358/Auxio_Fix.zip)

**Comment by KraXen72** [comment]
currently on cellular, will test when on stable connection.

**Comment by KraXen72** [comment]
i skipped like 10 times pretty quickly and it still crashed. (just searched a random artist and played that, then skipped a bunch)

**Comment by illdeletethis** [comment]
how can i turn the zip into something installable?

**Comment by OxygenCobalt** [comment]
@illdeletethis Rename the file extension from .zip to .apk.

@KraXen72 That is really weird. Can you take a stack trace for me? Seems like you can reproduce it reliably, and if it's not -1 positions then it's some other insanity.

**Comment by KraXen72** [comment]
how can i take a stack trace? through leakcanary? or? (i do have adb *i think* but haven't used it in a while)

**Comment by OxygenCobalt** [comment]
@KraXen72 Here's the steps I have in the issue template:

```
If possible, provide a stack trace or a Logcat. This can help identify the issue. 
To take a logcat, you must do the following:
1. Use a desktop/laptop to download the android platform tools from https://developer.android.com/studio/releases/platform-tools.
2. Extract the downloaded file to a folder.
3. Enable USB debugging on your phone [See https://developer.android.com/studio/command-line/adb#Enabling], and then connect your
phone to a laptop. You will get a prompt to "Allow USB debugging" when you run the logcat command. Accept this.
4. Open up a terminal/command prompt in that folder and run:
	- `./adb -d logcat | grep -i "[DWE] Auxio"` in the case of a bug [may require some changes on windows]
	- `./adb -d logcat AndroidRuntime:E *:S` in the case of a crash
5. Copy and paste the output to this area of the issue.
```

**Comment by KraXen72** [comment]
the crash on 2.6.3 stable: [current_stable.txt](https://github.com/OxygenCobalt/Auxio/files/10006999/current_stable.txt)
the crash on 2.6.3 debug: [debug_version.txt](https://github.com/OxygenCobalt/Auxio/files/10007000/debug_version.txt)

**Comment by OxygenCobalt** [comment]
Ughhhh, somehow the position is still managing to be -1. Guess I'll hack on some stupid UI fix instead of trying to fix the backend reporting -1 positions. If only `Slider` would gracefully degrade instead of crash with invalid positions.

**Comment by KraXen72** [comment]
yeah, that's a kind of thing you really shouldn't need to handle. maybe just wrap in in a try-catch and if it fails don't update slider pos/set to 0 when skipping?

**Comment by OxygenCobalt** [comment]
The issue is that `Slider` does not throw the error when you update the values, *it throws them when it tries to draw itself!* It is designed horribly for any use case that isn't changing settings.

**Comment by KraXen72** [comment]
>  If only `Slider` would gracefully degrade instead of crash with invalid positions.
i guess you *could* pr it to material components, but i've already seen how slow they've been with accepting more severe pr's you made, and it's really something you shouldn't have to worry about as a dev, smh

**Comment by OxygenCobalt** [comment]
[Auxio_FixedPositions.zip](https://github.com/OxygenCobalt/Auxio/files/10008659/Auxio_FixedPositions.zip)

Okay, how about this now? @KraXen72 @illdeletethis (Rename the extension to .APK from .ZIP)

**Comment by KraXen72** [comment]
it seems to be fixed in this apk - i can no longer reproduce it

**Comment by illdeletethis** [comment]
Tried every skip button and scroll to zero multiple times, no crash.
Thank you very much for your work.
Reading this thread, sorry for how many basics one should rely on are done so badly.
And hope your midterms went well.

**Comment by OxygenCobalt** [comment]
Okay, great. I think I'll be able to push out 2.6.4 with these changes tonight.
