### ISSUE TITLE
ReplayGain value is not reset upon switching music for a short period of time

### ISSUE THREAD

**Issue by ryenyuku** [OxygenCobalt/Auxio#389]
### Describe the Bug/Crash

1. Play an audio with a high RG's loudness value
2. Then play another audio with lower loudness value
3. Enjoy earrape jumpscare for a split second

### Describe the intended behavior

Auxio should reset the loudness value directly after playing a music

### What android version do you use?

Android 13

### What device model do you use?

Infinix Note 8 (LineageOS 20 GSI)

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by ryenyuku** [comment]
[Here's the screen recording](https://media.discordapp.net/attachments/718610371916726292/1081949638296342589/screen-20230305-122736.mp4) (I still can't upload it directly here 😅)

**Comment by OxygenCobalt** [comment]
I can't be sure if this is caused by a delay in metadata extraction or a delay in audio processing. I would have to look into it further.

**Comment by OxygenCobalt** [comment]
By the way, I can reproduce this issue. It really is an issue where the audio processor starts before it can actually apply the adjustment. I'll need to track the ReplayGain fields beforehand and apply them on song changes instead @ryenyuku.

**Comment by OxygenCobalt** [comment]
Hey @ryenyuku, can you try this APK? I've made the app dynamically apply adjustments instead.

[Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/11699542/Auxio_Canary.zip)

**Comment by ryenyuku** [comment]
> Hey @ryenyuku, can you try this APK? I've made the app cache applied adjustments instead of dynamically applying them. This seemingly works for me.
> 
> [Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/11699542/Auxio_Canary.zip)

Hmm, this build seems to completely ignore RG tag

**Comment by ryenyuku** [comment]
Nvm, upon further testing it looks like that it ignores some RG tags from specific audio. It seems to work for flac audio but not mp3?

**Comment by ryenyuku** [comment]
Uhh wait, this is weird. It seems to work for other mp3 audio too, but not for one audio. I'm sure that I've tagged it with a ReplayGain tag, and Musicolet (Pro) seems to confirm that. I'll send the audio as a sample.

**Comment by ryenyuku** [comment]
https://cdn.discordapp.com/attachments/718610371916726292/1116609507724902432/Bad_Wolves_-_Zombie_Orchestral_version.mp3

**Comment by ryenyuku** [comment]
I rechecked it with the latest stable release and it works fine too. Also I set the reference loudness to 98 dB and it seems to make quiet audio to be more louder and a bit distorted, so I recommend to turn the volume lower

**Comment by OxygenCobalt** [comment]
Okay, I identified the issue. Your files had partial adjustments (missing track or missing album) that Auxio was not recognizing due to a regression. Here's a new APK @ryenyuku:

[Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/11708229/Auxio_Canary.zip)

**Comment by ryenyuku** [comment]
> Okay, I identified the issue. Your files had partial adjustments (missing track or missing album) that Auxio was not recognizing due to a regression. Here's a new APK @ryenyuku:
> 
> [Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/11708229/Auxio_Canary.zip)

Thanks, this seems to fix the issue. But I've noticed that when I paused a song, the song got louder briefly before it got paused. It seems to very rarely happen as I can't reproduce it afterwards.

**Comment by OxygenCobalt** [comment]
> Thanks, this seems to fix the issue. But I've noticed that when I paused a song, the song got louder briefly before it got paused. It seems to very rarely happen as I can't reproduce it afterwards.

I've encountered this before and it seems to be a weird android-specific problem. Otherwise, this is great. Closing this issue.

**Comment by breversa** [comment]
Hello!
As of Auxio 3.4.3, I’m still having a similar-sounding issue: when switching from track to track (automatically or manually), sometimes ReplayGain seems to not be applied for the first 0-2 seconds.

**Comment by OxygenCobalt** [comment]
> Hello!
> As of Auxio 3.4.3, I’m still having a similar-sounding issue: when switching from track to track (automatically or manually), sometimes ReplayGain seems to not be applied for the first 0-2 seconds.

Yep, noticed this too. I need to make the audio processor solely use the player state rather than relying on callbacks.

**Comment by OxygenCobalt** [comment]
Update @breversa, this actually is a fundamental ExoPlayer issue documented at https://github.com/androidx/media/issues/418.

I'll have to understand the fork change that was steadily chipped away at in the issue discussion and then mangle my ExoPlayer fork to add it myself without destroying the entire audio playback system. Putting this on the backburner for now.

**Comment by OxygenCobalt** [comment]
@graphene1over I had to do some drastic refactors in 3.6.0 so I wouldn't be shocked if I knocked out some part of the ReplayGain system by accident. Will investigate but I don't know when I'll have time.

**Comment by OxygenCobalt** [comment]
This was fixed in 3.6.3 @graphene1over

**Comment by Kibodi** [comment]
When using the ReplayGain Track method, the behavior still occur. Tested in 3.6.3 and 4.0.0-dev.
I've generated some files where it happens to test it.

[auxiotest.tar.gz](https://github.com/user-attachments/files/18344109/auxiotest.tar.gz)

**Comment by OxygenCobalt** [comment]
This is fixable soon according to the ExoPlayer devs!

https://github.com/androidx/media/issues/418#issuecomment-4055038642
