### ISSUE TITLE
Music can no longer be found on v3.3.0 onwards

### ISSUE THREAD

**Issue by HeConnor** [OxygenCobalt/Auxio#662]
### Describe the Bug/Crash

In setting->music folder, I set **my own music folder path** to "include folder", but no music found. 

Then, I found "exclude and include folder" are all same **my own music folder path**. 

### Describe the intended behavior

In setting->music folder, I set **my own music folder path** to "include folder",  music can be found. 

"exclude folder" was empty.

### What android version do you use?

Android 10

### What device model do you use?

OnePlus 7T

### Bug report

The previous version was ok

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Can't reproduce this on my Android 14 device, let me check if its an accidental regression on Android 10 and below.

**Comment by OxygenCobalt** [comment]
I can't reproduce the behavior of them acting the same. I think the issue now is that Auxio can't load any music anymore. "Include folders" is a bit of bad naming since it's moreso restricting what music Auxio *can* find to a particular folder rather than telling Auxio to look for music in that folder.

Can you please try this Debug APK @HeConnor? I need you to take a bug report following [these instructions](https://developer.android.com/studio/debug/bug-report). There are also [instructions in Chinese/中文 – 简体](https://developer.android.com/studio/debug/bug-report?hl=zh-cn), if that helps.

**Comment by OxygenCobalt** [comment]
Here's the APK I want you to try @HeConnor

[Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/13846171/Auxio_Canary.zip)

**Comment by HeConnor** [comment]
Hello OxygenCobalt,
    1. I used [Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/13846171/Auxio_Canary.zip) on my phone, and return a dump file [2024-01-06_12-52-57_079.hprof..bin.zip](https://github.com/OxygenCobalt/Auxio/files/13848589/2024-01-06_12-52-57_079.hprof.bin.zip), (I can't read instructions, I hope it's helpful for you).
    2. I reinstall **version 3.2.1**, and then set **my own music folder path** to "include folder", **music can be found**. But  I found "exclude and include folder" are all same my own music folder path (it's same as version 3.3.0, but music can't be found in v3.3.0). You can see my screenshot:
![example](https://github.com/OxygenCobalt/Auxio/assets/22026546/4eb999bc-e27c-4bfd-b0e4-0cac8f98352d)

**Comment by OxygenCobalt** [comment]
Sadly, that file does not help. I'm also having trouble what you are communicating in the second statement.

In this case, if you cannot provide logs @HeConnor, I want you to test these APK files and tell me which ones work and which ones don't:

[Auxio_5562c184157c38a1ad2aed3d30388f41f6106c4f.zip](https://github.com/OxygenCobalt/Auxio/files/13850692/Auxio_5562c184157c38a1ad2aed3d30388f41f6106c4f.zip)
[Auxio_673629dd2639537c9e66ca38e8d6d15bd7157797.zip](https://github.com/OxygenCobalt/Auxio/files/13850693/Auxio_673629dd2639537c9e66ca38e8d6d15bd7157797.zip)
[Auxio_ec8e598d3bedfa7051e12ab1b60a4bb98c0be9bf.zip](https://github.com/OxygenCobalt/Auxio/files/13850694/Auxio_ec8e598d3bedfa7051e12ab1b60a4bb98c0be9bf.zip)

This will allow me to narrow down exactly where the app broke.

**Comment by HeConnor** [comment]
em... 
My work flow: 
 1. install app
 2. runing (Grant permissions)
 3. set my own music folder path to "include folder" and save setting
 4. scan music folder
 
**Only Auxio_5562.. is OK**!

**Comment by najdshad** [comment]
I have the same issue on my Samsung A53 (Android 14, One UI 6.0)

**Comment by Richard38907** [comment]
Same issue on my OnePlus Nord (PixelExperience - Android 13). V 3.3.0 only too.

**Comment by OxygenCobalt** [comment]
Alright, here's some more APKs to try @HeConnor @najdshad @Richard38907.

[Auxio_ec8e598.zip](https://github.com/OxygenCobalt/Auxio/files/13877612/Auxio_ec8e598.zip)
[Auxio_d59230b.zip](https://github.com/OxygenCobalt/Auxio/files/13877613/Auxio_d59230b.zip)
[Auxio_6956ca5.zip](https://github.com/OxygenCobalt/Auxio/files/13877614/Auxio_6956ca5.zip)

**Comment by OxygenCobalt** [comment]
If you also can @najdshad @Richard38907, please take a bug report once music loading fails using the [instructions here](https://developer.android.com/studio/debug/bug-report)

**Comment by Richard38907** [comment]
Bug report option is suddenly missing in my developer options. Is it possible to generate it from ADB instead?

**Comment by OxygenCobalt** [comment]
I think `adb bugreport` also works @Richard38907. Also, make sure you're doing the bug report when music loading fails in one of the debug builds (like [Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/13846171/Auxio_Canary.zip)).

**Comment by Richard38907** [comment]
![bugreport-CPH2415EEA-UKQ1.230924.001-2024-01-09-21-37-32-dumpstate_log-2570.txt](https://github.com/OxygenCobalt/Auxio/files/13878878/bugreport-CPH2415EEA-UKQ1.230924.001-2024-01-09-21-37-32-dumpstate_log-2570.txt)

![bugreport-CPH2415EEA-UKQ1.230924.001-2024-01-09-21-37-32.zip](https://github.com/OxygenCobalt/Auxio/files/13878879/bugreport-CPH2415EEA-UKQ1.230924.001-2024-01-09-21-37-32.zip)

![dumpstate-stats.txt](https://github.com/OxygenCobalt/Auxio/files/13878877/dumpstate-stats.txt)

![Screenshot_20240109-213900.png](https://github.com/OxygenCobalt/Auxio/assets/148692265/ade9be40-081c-4520-8b3f-30557b7882d1)

![Screenshot_20240109-213839.png](https://github.com/OxygenCobalt/Auxio/assets/148692265/bd9b330f-e6a8-4ef1-a738-6551a3b12e34)

![Screenshot_20240109-213656.png](https://github.com/OxygenCobalt/Auxio/assets/148692265/43f2b964-754c-4268-a156-3ac75247d00f)

I reproduced the bug on my OnePlus 10t (android 14)

The error is detailed here:

android.database.sqlite.SQLiteException: near "OR": syntax error (code 1 SQLITE_ERROR): , while compiling: SELECT _id, date_added, date_modified, _size, duration, mime_type, title, year, album, album_id, artist, album_artist, _display_name, volume_name, relative_path, cd_track_number, disc_number FROM audio WHERE ((((is_pending=0 AND NOT _modifier=4) OR (is_pending=1 AND lower(_data) NOT REGEXP '.*/\.pending-(\d+)-([^/]+)$' AND owner_package_name IN ( 'org.oxycblt.auxio' )))) AND (is_trashed=0) AND (volume_name IN ( 'external_primary' ))) AND (NOT _size=0 AND is_music=1 AND NOT  ( OR (volume_name LIKE ? AND relative_path LIKE ?)))
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:186)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:495)
	at android.content.ContentResolver.query(ContentResolver.java:1255)
	at android.content.ContentResolver.query(ContentResolver.java:1181)
	at android.content.ContentResolver.query(ContentResolver.java:1137)
	at org.oxycblt.auxio.music.fs.StorageUtilKt.safeQuery(Unknown Source:6)
	at org.oxycblt.auxio.music.fs.MediaStoreExtractorImpl.query(SourceFile:369)
	at org.oxycblt.auxio.music.MusicRepositoryImpl$indexImpl$mediaStoreQueryJob$1.invokeSuspend(SourceFile:37)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at androidx.fragment.app.Fragment$4.run(SourceFile:43)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:92)

**Comment by dreamsyntax** [comment]
Commenting as I've also ran into this on FDroid version. Will build your latest changes.

**Comment by OxygenCobalt** [comment]
Please respond with any kind of relevant log information @dreamsyntax!

**Comment by dreamsyntax** [comment]
> Please respond with any kind of relevant log information @dreamsyntax!

I saved this while still on the FDroid build
```
android.database.sqlite.SQLiteException: near "OR": syntax error (code 1 SQLITE_ERROR): , while compiling: SELECT _id, date_added, date_modified, _size, duration, mime_type, title, year, album, album_id, artist, album_artist, _display_name, volume_name, relative_path, cd_track_number, disc_number FROM audio WHERE ((((is_pending=0 AND NOT _modifier=4) OR (is_pending=1 AND lower(_data) NOT REGEXP '.*/\.pending-(\d+)-([^/]+)$' AND owner_package_name IN ( 'org.oxycblt.auxio' )))) AND (is_trashed=0) AND (volume_name IN ( 'external_primary' ))) AND (NOT _size=0 AND is_music=1 AND  ( OR (volume_name LIKE ? AND relative_path LIKE ?)))
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:186)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:495)
	at android.content.ContentResolver.query(ContentResolver.java:1235)
	at android.content.ContentResolver.query(ContentResolver.java:1167)
	at android.content.ContentResolver.query(ContentResolver.java:1123)
	at org.oxycblt.auxio.music.fs.StorageUtilKt.safeQuery(Unknown Source:6)
	at org.oxycblt.auxio.music.fs.MediaStoreExtractorImpl.query(SourceFile:369)
	at org.oxycblt.auxio.music.MusicRepositoryImpl$indexImpl$mediaStoreQueryJob$1.invokeSuspend(SourceFile:37)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at androidx.fragment.app.Fragment$4.run(SourceFile:43)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:92)
```

**Comment by OxygenCobalt** [comment]
Okay, that's the same error as everyone else but @HeConnor and @najdshad are seemingly facing.

**Comment by OxygenCobalt** [comment]
v3.3.1 should have a path for your issues @dreamsyntax @Richard38907 (I hope). Please test them as soon as possible.

**Comment by MysterioABC** [comment]
I actually faced a similar problem in v3.3.0, after updating to this version, "include folder" and "exclude folder" just stopped working. No matter which folder I add to either of them, it always loads all the music from all the storage (Internal + External). I have no visible error pop ups tho in regular released apk from github. I am on stock android 8.1 . Although in the previous version, both of them functions as expected. I downgraded to v3.2.1 for now.

**Comment by Ox55** [comment]
I was having the same problem on my device running **Android 13**, accessing the _/Library/Music Folders_ settings, I noticed that the app is adding the _/Include_ directories to _/Exclude_, making the app accept and at the same time reject processing music from these directories, I had to choose only one directory for the app to process music. In version 3.3.0 (F-Droid) it is no longer possible to add more than one directory in _/Include_ without giving an error, that is, _/Include_ must be limited to a single path, to run music in more than one directory you must remove both paths of _/Include_, _/Exclude_, I did not test if this results in error on **Huawei** devices.

**Comment by Ox55** [comment]
I was having the same problem on my device running **Android 13**, accessing the _/Library/Music Folders_ settings, I noticed that the app is adding the _/Include_ directories to _/Exclude_, making the app accept and at the same time reject processing music from these directories, I had to choose only one directory for the app to process music. In version 3.3.0 (F-Droid) it is no longer possible to add more than one directory in _/Include_ without giving an error, that is, _/Include_ must be limited to a single path, to run music in more than one directory you must remove both paths of _/Include_, _/Exclude_, I did not test if this results in error on **Huawei** devices.

**Comment by OxygenCobalt** [comment]
> I was having the same problem on my device running Android 13, accessing the /Library/Music Folders settings, I noticed that the app is adding the /Include directories to /Exclude, making the app accept and at the same time reject processing music from these directories

I don't really know what this means.

Anyway, I didn't actually fix the issue. It turns out there were two distinct issues that could both cause the same error, and I only fixed one.

**Comment by OxygenCobalt** [comment]
I've just released 3.3.2, which should at minimum fix the music loading failing. As for the broken include/exclude behavior, without any information I can't meaningfully resolve it.

**Comment by MysterioABC** [comment]
I just updated to latest version v 3.3.2 and unfortunately the issue is not resolved for my case yet. It could be a different one in my case than the logs available above. 

I describe it in detail, note it I am now on v3.3.2 and issue started to occur since updating to v3.3.0. There are two separate issues for me. Include folder & Exclude folder issue. 
**Include folder** : When I try to add any folder which has many music files (.mp3 specifically)(those files gets loaded along with all others when Include is empty!) it shows no music found pop-up. 
**Exclude folder** : When I try to add any folder, it just loads all the music files of whole device (Internal + External storage) regardless of whatever I added.

I tried debug version you mentioned above, but there's no visible error in my case as @Richard38907 showed in screenshots.

**Comment by OxygenCobalt** [comment]
What's your device version @MysterioABC?

**Comment by MysterioABC** [comment]
I am on stock android 8.1, motorola G5 plus

**Comment by OxygenCobalt** [comment]
Figured out the issue. I was selecting for some extremely malformed paths, something like `storage/emulated/0Music`. I believe I've fixed it now in this debug build, can you try it @MysterioABC?

[Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/13932627/Auxio_Canary.zip)

**Comment by MysterioABC** [comment]
Issue seems to be fixed in latest update you just pushed. Thank you!!

**Comment by dreamsyntax** [comment]
Is there a time window for F-Droid to host v3.3.3? I kept a bugged state to purposely test going from v3.3.0, but I'm stuck the F-Droid signed version.

**Comment by OxygenCobalt** [comment]
Yep, usually F-Droid does one big build job per week and so all releases are delayed. Extremely frustratingly, they picked up 3.3.1, which had the broken patch, but not 3.3.2 or 3.3.3 @dreamsyntax. 

This is really motivating me to revisit accrescent.

**Comment by dreamsyntax** [comment]
Last update from me, F-Droid finally pushed v3.3.3, and the install I persisted did properly recover the library and playlists once installed.
