### ISSUE TITLE
error loading library, syntax error

### ISSUE THREAD

**Issue by magowiz** [OxygenCobalt/Auxio#667]
### Describe the Bug/Crash

After updating I opened app and I get a dialog saying loading music failed, clicking more button I get syntax error
android.database.sqlite.SQLiteException: near "OR": syntax error (code 1 SQLITE_ERROR): , while compiling: SELECT _id, date_added, date_modified, _size, duration, mime_type, title, year, album, album_id, artist, album_artist, _display_name, volume_name, relative_path, cd_track_number, disc_number FROM audio WHERE ((is_pending=0 OR (is_pending=1 AND lower(_data) NOT REGEXP '.*/\.pending-(\d+)-([^/]+)$' AND owner_package_name IN ( 'org.oxycblt.auxio' ))) AND (is_trashed=0) AND (volume_name IN ( 'external_primary' ))) AND (NOT _size=0 AND is_music=1 AND NOT  ( OR (volume_name LIKE ? AND relative_path LIKE ?)))
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:186)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:472)
	at android.content.ContentResolver.query(ContentResolver.java:1195)
	at android.content.ContentResolver.query(ContentResolver.java:1127)
	at android.content.ContentResolver.query(ContentResolver.java:1083)
	at org.oxycblt.auxio.music.fs.StorageUtilKt.safeQuery(Unknown Source:6)
	at org.oxycblt.auxio.music.fs.MediaStoreExtractorImpl.query(SourceFile:369)
	at org.oxycblt.auxio.music.MusicRepositoryImpl$indexImpl$mediaStoreQueryJob$1.invokeSuspend(SourceFile:37)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at androidx.fragment.app.Fragment$4.run(SourceFile:43)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:92)

### Describe the intended behavior

Should load music successfully

### What android version do you use?

Android 11

### What device model do you use?

Xiaomi Redmi Note 8 Pro

### Bug report

N

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by magowiz** [comment]
I was able to make this work again deleting app data then I found that the error comes out if I have 2 folders in exclude list, if I add a folder to exclude goes fine, if I add a second one the error comes out, if I remove second folder works again, so it seems an issue on how the SQL query is constructed with 2 (or more) folders to exclude.

**Comment by OxygenCobalt** [comment]
This is fixed in the development branch. I'll pin it for now.

**Comment by magowiz** [comment]
The issue is still there in 3.3.1 when excluding more than one folder:
`android.database.sqlite.SQLiteException: near "OR": syntax error (code 1 SQLITE_ERROR): , while compiling: SELECT _id, date_added, date_modified, _size, duration, mime_type, title, year, album, album_id, artist, album_artist, _display_name, volume_name, relative_path, cd_track_number, disc_number FROM audio WHERE ((is_pending=0 OR (is_pending=1 AND lower(_data) NOT REGEXP '.*/\.pending-(\d+)-([^/]+)$' AND owner_package_name IN ( 'org.oxycblt.auxio' ))) AND (is_trashed=0) AND (volume_name IN ( 'external_primary' ))) AND (NOT _size=0 AND is_music=1 AND NOT  ( OR (volume_name LIKE ? AND relative_path LIKE ?)))
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:186)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:472)
	at android.content.ContentResolver.query(ContentResolver.java:1195)
	at android.content.ContentResolver.query(ContentResolver.java:1127)
	at android.content.ContentResolver.query(ContentResolver.java:1083)
	at org.oxycblt.auxio.music.fs.StorageUtilKt.safeQuery(Unknown Source:6)
	at org.oxycblt.auxio.music.fs.MediaStoreExtractorImpl.query(SourceFile:377)
	at org.oxycblt.auxio.music.MusicRepositoryImpl$indexImpl$mediaStoreQueryJob$1.invokeSuspend(SourceFile:37)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at androidx.fragment.app.Fragment$4.run(SourceFile:43)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:92)
`

**Comment by magowiz** [comment]
Sorry I misunderstood, the release with the fix will be 3.3.3 I thought it could it be next one after closing this, I didn't know about delay between your release and f-droid publish.
